repository: HlidacStatu/hlidacstatu.github.io
gems:
  - jekyll-github-metadata

selected_repositories:
  Hlídač státu:
    - HlidacStatu
    - Datasety
    - API
  Veřejné zakázky:
    - verejne-zakazky
  Ostatní:
    - volicsky-prukaz
    - Wordpress-plugin
